version: '2'

services:

  website:
    build:
      context: .
      dockerfile: Website-Dockerfile
    expose:
      - "80"
      - "443"
    ports:
      - "1883:1883"
    volumes:
      - /etc/letsencrypt/live/www.lambdaspace.gr:/etc/letsencrypt/live/www.lambdaspace.gr:ro
      - /etc/letsencrypt/archive/www.lambdaspace.gr:/etc/letsencrypt/archive/www.lambdaspace.gr:ro

  proxy:
    build:
      context: .
      dockerfile: HAProxy-Dockerfile
    links:
      - website
    external_links:
      - app:discourse
    ports:
      - "80:80"
      - "443:443"

  ministerin:
    build:
      context: .
      dockerfile: MinisterIN-Dockerfile
    ports:
      - "7777:7777"
