version: '3.2'

services:
  rancher:
    image: rancher/rancher
    restart: unless-stopped
#    ports:
#      - "8080:80"
#      - "8443:443"
  lapi:
    build:
      context: .
      dockerfile: lapi.dockerfile
    restart: unless-stopped
  caddy:
    image: abiosoft/caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - 80:80
      - 443:443
    links:
      - lapi
      - rancher
