version: '3.2'

services:
  rancher:
    image: rancher/server:preview
    restart: unless-stopped
    ports:
      - "8080:8080"
  lapi:
    build:
      context: .
      dockerfile: lapi.dockerfile
    restart: unless-stopped
  caddy:
    image: abiosoft/caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - 80:80
      - 443:443
    links:
      - lapi
